apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
      - name: adminer
        image: adminer:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: adminer-service
spec:
  type: ClusterIP
  selector:
    app: adminer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: adminer-auth
spec:
  basicAuth:
    secret: adminer-auth
---
apiVersion: v1
kind: Secret
metadata:
  name: adminer-auth
  namespace: default
type: kubernetes.io/basic-auth
data:
  username: YWxla3MtYXBwLWFkbWlu # aleks-app-admin
  password: bnp1cTk4MW1qeA== # nzuq981mjx