apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: acme
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: acme
    solvers:
      - http01:
          ingress:
            ingressClassName: traefik
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: common-cert
spec:
  secretName: tls-prod
  dnsNames:
    - web.app-aleks.de
    - web.backend.app-aleks.de
    - web.staging.app-aleks.de
    - web.staging.backend.app-aleks.de
  issuerRef:
    name: acme
    kind: Issuer
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    # traefik.ingress.kubernetes.io/router.entrypoints: websecure
    # traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - web.staging.app-aleks.de
    secretName: tls-prod
  rules:
  - host: web.app-aleks.de
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: aleks-web-service
            port:
              number: 80
  - host: web.backend.app-aleks.de
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: aleks-backend-service
            port:
              number: 80
  - host: web.staging.app-aleks.de
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: aleks-web-staging-service
            port:
              number: 80
  - host: web.staging.backend.app-aleks.de
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: aleks-backend-staging-service
            port:
              number: 80
