apiVersion: apps/v1
kind: Deployment
metadata:
  name: aleks-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aleks-backend
  template:
    metadata:
      labels:
        app: aleks-backend
    spec:
      containers:
      - name: aleks-backend
        image: europe-west3-docker.pkg.dev/aleks-app/cloud-run-source-deploy/aleks-backend-v3/aleks-backend-v3:latest
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: aleks-backend-env
      imagePullSecrets:
      - name: registry-access-europe-west3
---
apiVersion: v1
kind: Service
metadata:
  name: aleks-backend-service
spec:
  type: ClusterIP
  selector:
    app: aleks-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000